<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Nivea Men dry impact anti-transpirant roller',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393635363837?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'ml',
                'id_category' => 1,
                'weight' => '50',
            ],
            [
                'name' => 'Colgate Tandpasta Sensation White',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393637393934?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'ml',
                'id_category' => 1,
                'weight' => '75',
            ],
            [
                'name' => 'Ultra Doux Shampoo kamille bloemenhoning bel',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239383933373530?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'ml',
                'id_category' => 1,
                'weight' => '250',
            ],
            [
                'name' => 'Sunlight Classic care shower & bath bel',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393931363531?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'l',
                'id_category' => 1,
                'weight' => '0.68',
            ],
            [
                'name' => 'Listerine Mondwater total care',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393430393133?revLabel=2&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'l',
                'id_category' => 1,
                'weight' => '0.5',
            ],
            [
                'name' => 'Whiskas Temptations kip & kaas kattensnacks',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303832313338?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 2,
                'weight' => '60',
            ],
            [
                'name' => 'Cesar Classic met rund',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239373933343439?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 2,
                'weight' => '150',
            ],
            [
                'name' => 'Purina ONE Junior 1-12 maanden rijk aan kip',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303432363433?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 2,
                'weight' => '800',
            ],
            [
                'name' => 'Sheba Classics pat met kip',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303135343134?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 2,
                'weight' => '85',
            ],
            [
                'name' => 'Felix Soup original 6-pack',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303534343234?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 2,
                'weight' => '6 x 48',
            ],
            [
                'name' => 'Lay\'s Oven baked naturel',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239373932383630?revLabel=2&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 3,
                'weight' => '150',
            ],
            [
                'name' => 'LU Tuc bake rolls sea salt',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303433343736?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 3,
                'weight' => '150',
            ],
            [
                'name' => 'Doritos Sweet chilli pepper',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393933393838?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 3,
                'weight' => '170',
            ],
            [
                'name' => 'Lay\'srills',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239373936313135?revLabel=3&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 3,
                'weight' => '125',
            ],
            [
                'name' => 'Cheetos Chipito kaas',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239373935363732?revLabel=4&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 3,
                'weight' => '125',
            ],
            [
                'name' => 'Alpro Haverdrink zonder suikers',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393837313331?revLabel=1&rendition=400x400_JPG_Q85&fileType=binary',
                'status' => true,
                'presentation' => 'l',
                'id_category' => 4,
                'weight' => '1',],
            [
                'name' => 'Activia Yoghurt vanille',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303831323433?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 4,
                'weight' => '4 x 125',
            ],
            [
                'name' => 'PHILADELPHIA GOAT CHEESE AND ROSEMARY 150g',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393933323238?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 4,
                'weight' => '150',
            ],
            [
                'name' => 'OIKOS GREEK YOGHURT 480g',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303639313731?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 4,
                'weight' => '480',
            ],
            [
                'name' => 'HiPRO Mousse chocola bel',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393334393331?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 4,
                'weight' => '200',
            ],
            [
                'name' => 'Kellogg\'s Tresor melk choco',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303735393736?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 5,
                'weight' => '410',
            ],
            [
                'name' => 'Kellogg\'s Mini\'s',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393635353932?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 5,
                'weight' => '215',
            ],
            [
                'name' => 'Quaker Cruesli chocolade',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303038383938?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 5,
                'weight' => '450',
            ],
            [
                'name' => 'Quakerranola nuts & seeds',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239373932393437?revLabel=2&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 5,
                'weight' => '450',
            ],
            [
                'name' => 'Jordans Simply crunchy honey bakedranola',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303639353030?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 5,
                'weight' => '700',
            ],
            [
                'name' => 'Pampers Baby dry pantsuierbroekjes maat 6',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303336353936?revLabel=2&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'stuks',
                'id_category' => 6,
                'weight' => '20',
            ],
            [
                'name' => 'Lulu betterfood plet bel',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393332313334?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 6,
                'weight' => '175',
            ],
            [
                'name' => 'Organix Apple rice cake clouds 7m+',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393138383332?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 6,
                'weight' => '40',
            ],
            [
                'name' => 'Nestlé Yogolino aardbei 6m+',
                'picture' => 'https://static.ah.nl/dam/product/AHI_4354523130303733383033?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 6,
                'weight' => '400',
            ],
            [
                'name' => 'Nutrilon 1 volledige zuigelingenvoeding 0-6m',
                'picture' => 'https://static.ah.nl/dam/product/AHI_43545239393036333438?revLabel=1&rendition=800x800_JPG_Q90&fileType=binary',
                'status' => true,
                'presentation' => 'g',
                'id_category' => 6,
                'weight' => '800',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}

